
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 19
y = 19

[general]
live_config_reload = true
import = ["/home/ivan/.config/alacritty/colorschemes/onedark.toml", "/home/ivan/.config/alacritty/fonts.toml"]
